### ISSUE TITLE
test的时候报错 OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by Vuscity** [ProHiryu/bert-chinese-ner#26]
自己的数据集（train和dev没问题）
进行test的时候报错：
INFO:tensorflow:*** Example ***
INFO:tensorflow:guid: test-4
INFO:tensorflow:tokens: 岳 红 朋 友 否 认 此 事 , 警 方 已 成 立 专 案 组 调 查 前 晚 1 0 时 许 , 著 名 演 员 岳 红 被 一 男 子 以 商 谈 拍 片 之 事 约 至 世 纪 金 源 大 饭 店 , 随 即 被 持 刀 威 胁 勒 索 5 万 元 , 后 经 岳 红 报 警 并 逃 脱
INFO:tensorflow:input_ids: 101 2277 5273 3301 1351 1415 6371 3634 752 117 6356 3175 2347 2768 4989 683 3428 5299 6444 3389 1184 3241 122 121 3198 6387 117 5865 1399 4028 1447 2277 5273 6158 671 4511 2094 809 1555 6448 2864 4275 722 752 5276 5635 686 5279 7032 3975 1920 7649 2421 117 7390 1315 6158 2898 1143 2014 5516 1239 5164 126 674 1039 117 1400 5307 2277 5273 2845 6356 2400 6845 5564 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
INFO:tensorflow:input_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
INFO:tensorflow:segment_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
INFO:tensorflow:label_ids: 9 2 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 3 1 1 1 1 1 10 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
Traceback (most recent call last):
  File "BERT_NER.py", line 621, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "BERT_NER.py", line 592, in main
    predict_file,mode="test")
  File "BERT_NER.py", line 303, in filed_based_convert_examples_to_features
    feature = convert_single_example(ex_index, example, label_map, max_seq_length, tokenizer,mode)
  File "BERT_NER.py", line 286, in convert_single_example
    write_tokens(ntokens,mode)
  File "BERT_NER.py", line 211, in write_tokens
    wf.close()
OSError: [Errno 5] Input/output error
请问如何解决呢？

**Comment by Vuscity** [comment]
是google colab的问题。已解决。
