### ISSUE TITLE
tensorflow.python.framework.errors_impl.FailedPreconditionError: output/result_dir/train.tf_record; Is a directory

### ISSUE THREAD

**Issue by lzh66** [ProHiryu/bert-chinese-ner#61]
Traceback (most recent call last):
  File "BERT_NER.py", line 621, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "BERT_NER.py", line 544, in main
    train_examples, label_list, FLAGS.max_seq_length, tokenizer, train_file)
  File "BERT_NER.py", line 299, in filed_based_convert_examples_to_features
    writer = tf.python_io.TFRecordWriter(output_file)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/tf_record.py", line 218, in __init__
    compat.as_bytes(path), options._as_record_writer_options(), status)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/errors_impl.py", line 548, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: output/result_dir/train.tf_record; Is a directory

请问这是怎么回事呢

**Comment by thunderVolibear** [comment]
output/result_dir/手动创建这个路径就行了
